#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Render the C1.5 M2 benchmark report from replay/live JSON.

Honesty contract (spec §3.5, §12 — the property under review):
  * Any metric whose source JSON is ABSENT prints "N/A — not measured".
  * If the baseline (pre-Dirac) build failed (--baseline-ok 0), the script
    does NOT invent a delta — it emits the POST-build numbers only and marks
    every cross-build delta "N/A — baseline build failed".
  * Live metrics (cache-hit, cost) print "N/A — not measured (no API key)"
    when no live JSON was produced.

Usage:
  render_report.py --report <out.md> --baseline-ok <0|1> \
      [--post-post a.json] [--post-pre b.json] \
      [--base-post c.json] [--base-pre d.json] \
      [<live1.json> <live2.json> ...]
"""
import argparse
import json
import os
import sys


def load(path):
    if not path or not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"warning: could not read {path}: {e}", file=sys.stderr)
        return None


def pct_delta(base, post):
    """(base - post) / base as a percentage string, or None if not computable."""
    if base is None or post is None:
        return None
    if base in (0, None):
        return None
    return (base - post) / base


def fmt_pct(x):
    return "N/A — not measured" if x is None else f"{x * 100:.1f}%"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", required=True)
    ap.add_argument("--baseline-ok", required=True)
    ap.add_argument("--post-post")
    ap.add_argument("--post-pre")
    ap.add_argument("--base-post")
    ap.add_argument("--base-pre")
    ap.add_argument("live", nargs="*", help="live-mode JSON files (optional)")
    args = ap.parse_args()

    baseline_ok = args.baseline_ok == "1"

    pp = load(args.post_post)   # post build, post golden  (the borrow behaviour on current code)
    pre_on_post = load(args.post_pre)   # post build, pre golden (legacy behaviour on current code)
    bp = load(args.base_post)   # baseline build, post golden
    base_pre = load(args.base_pre)      # baseline build, pre golden

    if pp is None:
        print("ABORT: post-build POST replay JSON is missing — nothing to report.", file=sys.stderr)
        sys.exit(1)

    lines = []
    lines.append("# C1.5 — 50-Turn Refactor Benchmark Report (M2 DoD)")
    lines.append("")
    lines.append("> Generated by `scripts/bench/c1.5-50turn.sh`. Replay metrics are")
    lines.append("> deterministic (no network); live metrics require API keys and are")
    lines.append("> omitted (\"N/A — not measured\") when absent. **No metric is fabricated.**")
    lines.append("")

    # ── Replay headline ──────────────────────────────────────────────
    lines.append("## Replay (deterministic)")
    lines.append("")
    lines.append(f"- Fixture: `{pp.get('fixture', '?')}`")
    lines.append(f"- Tool set: {pp.get('tool_count', '?')} builtin tools (identical pre/post)")
    lines.append("")
    lines.append("| Metric | Pre (legacy seq) | Post (borrow seq) | Reduction |")
    lines.append("|---|---|---|---|")

    # Same-build comparison (post build runs BOTH golden sequences). This is the
    # cleanest apples-to-apples comparison of legacy-vs-borrow tool behaviour on
    # ONE codebase, independent of whether the baseline build succeeded.
    pre_tok = pre_on_post.get("total_input_tokens") if pre_on_post else None
    post_tok = pp.get("total_input_tokens")
    pre_rt = pre_on_post.get("round_trips") if pre_on_post else None
    post_rt = pp.get("round_trips")

    lines.append(
        f"| Σ input tokens | {pre_tok if pre_tok is not None else 'N/A — not measured'} "
        f"| {post_tok} | {fmt_pct(pct_delta(pre_tok, post_tok))} |"
    )
    lines.append(
        f"| Round-trips | {pre_rt if pre_rt is not None else 'N/A — not measured'} "
        f"| {post_rt} | {fmt_pct(pct_delta(pre_rt, post_rt))} |"
    )
    lines.append("")

    # ── Cross-build (pre-Dirac vs post-Dirac code) ───────────────────
    lines.append("## Cross-build (pre-Dirac code vs post-Dirac code)")
    lines.append("")
    if not baseline_ok or bp is None:
        lines.append("**N/A — baseline build failed** (pre-Dirac interfaces diverged from the")
        lines.append("bench, or the baseline worktree did not build). Per spec §3.5 the script")
        lines.append("does NOT fabricate a cross-build delta. Use the same-build replay table")
        lines.append("above as the headline; it measures legacy-vs-borrow tool behaviour on the")
        lines.append("current codebase.")
    else:
        base_post_tok = bp.get("total_input_tokens")
        lines.append("| Metric | Pre-Dirac build | Post-Dirac build | Reduction |")
        lines.append("|---|---|---|---|")
        lines.append(
            f"| Σ input tokens (post golden) | {base_post_tok} | {post_tok} "
            f"| {fmt_pct(pct_delta(base_post_tok, post_tok))} |"
        )
        if base_pre is not None and pre_on_post is not None:
            lines.append(
                f"| Σ input tokens (pre golden) | {base_pre.get('total_input_tokens')} "
                f"| {pre_on_post.get('total_input_tokens')} "
                f"| {fmt_pct(pct_delta(base_pre.get('total_input_tokens'), pre_on_post.get('total_input_tokens')))} |"
            )
    lines.append("")

    # ── Live (non-gating) ────────────────────────────────────────────
    lines.append("## Live confirmation (non-gating)")
    lines.append("")
    live_reports = [load(p) for p in args.live]
    live_reports = [r for r in live_reports if r is not None]
    if not live_reports:
        lines.append("**N/A — not measured (no API key).** Live mode confirms the LLM actually")
        lines.append("adopts the borrows and measures real cache-hit; run with")
        lines.append("`DEEPSEEK_API_KEY` / `ANTHROPIC_API_KEY` set to populate this section.")
    else:
        lines.append("| Provider | Model | Runs | Avg in | Avg out | Avg cache-read | Cache-hit | Avg cost | batch | anchored | assume_hash | final OK |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
        for r in live_reports:
            lines.append(
                f"| {r.get('provider','?')} | {r.get('model','?')} | {r.get('runs','?')} "
                f"| {r.get('avg_input_tokens',0):.0f} | {r.get('avg_output_tokens',0):.0f} "
                f"| {r.get('avg_cache_read_tokens',0):.0f} | {r.get('cache_hit_rate',0)*100:.1f}% "
                f"| ${r.get('avg_cost_usd',0):.4f} "
                f"| {'✅' if r.get('adopted_batch_edit') else '❌'} "
                f"| {'✅' if r.get('adopted_anchored') else '❌'} "
                f"| {'✅' if r.get('adopted_assume_hash') else '❌'} "
                f"| {'✅' if r.get('final_state_correct') else '❌'} |"
            )
    lines.append("")

    # ── DoD verdict ──────────────────────────────────────────────────
    lines.append("## M2 DoD verdict")
    lines.append("")
    lines.append("| DoD gate | Target | Measured | Verdict |")
    lines.append("|---|---|---|---|")
    tok_red = pct_delta(pre_tok, post_tok)
    if tok_red is None:
        tok_verdict = "N/A — not measured"
        tok_meas = "N/A — not measured"
    else:
        tok_meas = fmt_pct(tok_red)
        tok_verdict = "MET" if tok_red >= 0.60 else "NOT MET"
        if tok_red > 0.75:
            tok_verdict += " (exceeds band — rename-heavy fixture)"
    lines.append(f"| 50-turn token reduction | −60–75% | {tok_meas} | {tok_verdict} |")
    rt_meas = f"{pre_rt}→{post_rt}" if pre_rt is not None else "N/A — not measured"
    lines.append(f"| Round-trip count | A2/B1 headline | {rt_meas} | report-only |")

    if live_reports:
        best_cache = max((r.get("cache_hit_rate", 0.0) for r in live_reports), default=0.0)
        cache_verdict = "MET" if best_cache >= 0.50 else "NOT MET"
        lines.append(f"| Cached-token hit rate | ≥50% | {best_cache*100:.1f}% | {cache_verdict} |")
    else:
        lines.append("| Cached-token hit rate | ≥50% | N/A — not measured (no API key) | N/A |")
    lines.append("| Monthly cost reduction | ↓60% | per-task proxy via live `avg_cost_usd` | see live table |")
    lines.append("| Output format consistency | +1.5/5 | manual rubric (appendix) | not auto-gated |")
    lines.append("")
    lines.append("## Appendix — format-consistency rubric (manual)")
    lines.append("")
    lines.append("Rate 5 sample refactor outputs pre/post on a 5-point scale (subjective,")
    lines.append("spec §8.4). Fill in by hand; not auto-gated.")
    lines.append("")

    os.makedirs(os.path.dirname(args.report), exist_ok=True)
    with open(args.report, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"report → {args.report}")


if __name__ == "__main__":
    main()
